export default {
  Login: 'تسجيل الدخول',
  Register: 'تسجيل جديد',
  'Forgot Password': 'نسيت كلمة المرور',
  Profile: 'حسابي',
  Save: 'حفظ',
  Logout: 'تسجل الخروج',
  Home: 'الرئيسية',
  password: 'كلمة المرور',
  Phone: 'رقم الهاتف',
  Email: 'البريد الإلكتروني',
  'First name': 'الاسم الاول',
  'Last name': 'الاسم الاخير',
  Send: 'إرسال',
  Favoriets: 'المفضلة',
  Voucher: 'فاتورة',
  'My Orders': 'طلباتي',
  Offers: 'عروض',
  Settings: 'إعدادات',
  Suport: 'فريق الدعم',
  Apply: 'أضف',
  'Add Voucher': 'إضافة قسيمة',
  'Deliver To': 'التوصيل الى',
  'What You Are Looking For ?': 'ما الذي تبحث عنه؟',
  'Explore Category': 'استعرض الفئات',
  'View All': 'عرض الكل',
  "Continue":"استمرار",
  "Choose Country":"أختر الدولة",
  "Egypt":"مصر",
  "Bahrian":"البحرين",
  "take Care Of Your Body":"المنتج الاول للعناية بالبشرة",
  "But i must explain to you how all":"اطلبه الان و استمتع بافضل الخصومات علي منتجاتنا",
  "Order Now":"أطلب الأن",
  "Upload Prescription":"قم برفع الروشته",
  "And We Will Respond As Sonn As Possible":"و سوف نقوم بالرد عليك في اسرع وقت",
  "Upload Now":"ارفع الان",
  "This Service Allow You to Take Photo of your prescription or photo of the product and we will get back to you with the price and full details in seconds":
  "هذه الخدمة تتيح لك ان تأخذ صورة للروشتة الخاصة بك او ان ترفع صورة لمنتج تريده و سوف نرد عليك بالتفاصيل الكاملة في خلال دقائق معدوده",
  "RX":"روشتة",
  "We are here to serve you, select one of the tow options":"نحن هنا لنقدم افضل خدمة لك من فضلك اختر من احد الاختيارين التاليين",
  "Please Select":"من فضلك أختر",
  "Prescription With Insurance":"روشتة بتأمين",
  "Prescription Without Insurance":"روشتة بدون تأمين",
  "Upload File":"ارفع الملف",
  "RX Without Insurance":"روشتة بدون تأمين",
  "take photo to your prescription or photo of the product and press submit, and we will get back to you with the price and full details in seconds":
  "التقط صورة للروشتة الخاصة بك او ارفع صورة المنتج الذي تريده ز ثم اضفع علي تأكيد و سوف نقوم بالرد في ثوان معدودة",
  "File Name Here":"أسم الملف هنا",
  "request in progress":"طلبك قيد التنفيذ",
  "our pharmacist working now to give you the best price and full product instructions":"الروشتة الخاصة بك تراجع الان بواسطة افضل الصيادلة ليعطوك التفاصيل الكاملة",
  "Please wait while checking by":"من فضلك انتظر حتي تتم المراجعة بواسطة ",
  "Alexandria":"الاسكندرية",
  "Miami":"ميامي",
  "Min":"دقيقة",
  "Sec":"ثانية",
  "Cancel Request":"الغاء الطلب",
  "your prescription is tow steps from your home, proceed the order or add new product":
  "الروشتة الخاصة بك علي بعد خطوتين نت التوصيل لمنزلك قم بمراجعة و تأكيد و اضافة المنتجات للتوصيل",
  "DR":"دكتور",
  "Your Prescription Has Been Checked By":"تمت مراجعة الروشتة الخاصة بك بواسطة صيدلية",
  "Price":"السعر",
  "Quantity":"الكمية",
  "Tab":"شريط",
  "Dosage":"الجرعه",
  "2 Times Per Day - 1 Week":"مرتين في اليوم لمدة اسبوع",
  "Product Name Here":"أسم المنتج هنا",
  "Total Prescription Price":"اجمالي سعر الروشتة",
  "Your Order Will Be Delivered Within 30 Min":
  "طلبك سوف يتم توصيله في خلال 30 دقيقة",
  "Add To Wishlist":"اضافة الي المفضله",
  "Add To Cart":"اضافة الي السله",
  "Cart":"السلة",
  "Total":"الأجمالي",
  "Add Voucher Or Coupon":"اضف كوبون او كود خصم",
  "Cart Total":"اجمالي السلة",
  "Services Charge":"خدمة",
  "Discount":"خصم",
  "Total Amount":"الاجمالي",
  "Add More Items":"أضف المزيد",
  "Check Out":"تنفيذ الطلب",
  "Hi":"مرحبا",
  "Lets Place Your Order":"دعنا نضع طلبك",
  "Ahmed Mohamed":"احمد محمد",
  "st.12 - Building 20":"شارع 12 - عمارة رقم 20",
  "Mobile Number":"تليفون:",
  "Pay With":"الدفع بواسطة",
  "Cash By Deliver":"نقدي عند التسليم",
  "Online Payment":"الدفع اونلاين",
  "Payment Summery":"ملخص الدفع",
  "Place Order":"تنفيذ الطلب"
};
