export default {
  Login: 'تسجيل الدخول',
  Register: 'تسجيل جديد',
  'Forgot Password': 'نسيت كلمة المرور',
  Profile: 'الملف الشخصي',
  Save: 'حفظ',
  Logout: 'تسجل الخروج',
  Home: 'الرئيسية',
  password: 'كلمة المرور',
  Phone: 'رقم الهاتف',
  Email: 'البريد الإلكتروني',
  'First name': 'الاسم الاول',
  'Last name': 'الاسم الاخير',
  Send: 'إرسال',
  Favoriets: 'المفضلة',
  Voucher: 'فاتورة',
  'My Orders': 'طلباتي',
  Offers: 'عروض',
  Settings: 'إعدادات',
  Suport: 'فريق الدعم',
  Apply: 'تقديم',
  'Add Voucher': 'إضافة قسيمة',
  'Deliver To': 'التوصيل الى',
  'What You Are Looking For ?': 'ما الذي تبحث عنه؟',
  'Explore Category': 'استعرض الفئات',
  'View All': 'عرض الكل',
};
