export default {
  Login: 'تسجيل الدخول',
  Register: 'تسجيل جديد',
  'Forgot Password': 'نسيت كلمة المرور',
  Profile: 'حسابي',
  Save: 'حفظ',
  Logout: 'تسجل الخروج',
  Home: 'الرئيسية',
  password: 'كلمة المرور',
  Phone: 'رقم الهاتف',
  Email: 'البريد الإلكتروني',
  'First name': 'الاسم الاول',
  'Last name': 'الاسم الاخير',
  Send: 'إرسال',
  Favoriets: 'المفضلة',
  Voucher: 'فاتورة',
  'My Orders': 'طلباتي',
  Offers: 'عروض',
  Settings: 'إعدادات',
  Suport: 'فريق الدعم',
  Apply: 'تقديم',
  'Add Voucher': 'إضافة قسيمة',
  'Deliver To': 'التوصيل الى',
  'What You Are Looking For ?': 'ما الذي تبحث عنه؟',
  'Explore Category': 'استعرض الفئات',
  'View All': 'عرض الكل',
  "Continue":"استمرار",
  "Choose Country":"أختر الدولة",
  "Egypt":"مصر",
  "Bahrian":"البحرين",
  "take Care Of Your Body":"المنتج الاول للعناية بالبشرة",
  "But i must explain to you how all":"اطلبه الان و استمتع بافضل الخصومات علي منتجاتنا",
  "Order Now":"أطلب الأن",
  "Upload Prescription":"قم برفع الروشته",
  "And We Will Respond As Sonn As Possible":"و سوف نقوم بالرد عليك في اسرع وقت",
  "Upload Now":"ارفع الان",
  "This Service Allow You to Take Photo of your prescription or photo of the product and we will get back to you with the price and full details in seconds":
  "هذه الخدمة تتيح لك ان تأخذ صورة للروشتة الخاصة بك او ان ترفع صورة لمنتج تريده و سوف نرد عليك بالتفاصيل الكاملة في خلال دقائق معدوده",
  "RX":"روشتة",
  "We are here to serve you, select one of the tow options":"نحن هنا لنقدم افضل خدمة لك من فضلك اختر من احد الاختيارين التاليين",
  "Please Select":"من فضلك أختر",
  "Prescription With Insurance":"روشتة بتأمين",
  "Prescription Without Insurance":"روشتة بدون تأمين",
  "Upload File":"ارفع الملف",
  "RX Without Insurance":"روشتة بدون تأمين",
  "take photo to your prescription or photo of the product and press submit, and we will get back to you with the price and full details in seconds":
  "التقط صورة للروشتة الخاصة بك او ارفع صورة المنتج الذي تريده ز ثم اضفع علي تأكيد و سوف نقوم بالرد في ثوان معدودة",
  "File Name Here":"أسم الملف هنا",
  "request in progress":"طلبك قيد التنفيذ",
  "our pharmacist working now to give you the best price and full product instructions":"الروشتة الخاصة بك تراجع الان بواسطة افضل الصيادلة ليعطوك التفاصيل الكاملة",
  "Please wait while checking by":"من فضلك انتظر حتي تتم المراجعة بواسطة ",
  "Alexandria":"الاسكندرية",
  "Miami":"ميامي",
  "Min":"دقيقة",
  "Sec":"ثانية",
  "Cancel Request":"الغاء الطلب"
};
